# Generated by Django 4.1 on 2023-12-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="notice_board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField()),
                ("name", models.CharField(max_length=210)),
                ("title", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=2000)),
                ("postdate", models.DateTimeField(verbose_name="sysdate")),
                ("visitcount", models.IntegerField(verbose_name=6)),
            ],
        ),
    ]
