# Generated by Django 4.1 on 2023-12-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("user_pw", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("date_joined", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="question_board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_num", models.IntegerField()),
                ("q_name", models.CharField(max_length=210)),
                ("q_title", models.CharField(max_length=200)),
                ("q_content", models.CharField(max_length=2000)),
                ("q_postdate", models.DateTimeField(verbose_name="sysdate")),
                ("q_visitcount", models.IntegerField(verbose_name=6)),
            ],
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="content",
            new_name="n_content",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="name",
            new_name="n_name",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="num",
            new_name="n_num",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="postdate",
            new_name="n_postdate",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="title",
            new_name="n_title",
        ),
        migrations.RenameField(
            model_name="notice_board",
            old_name="visitcount",
            new_name="n_visitcount",
        ),
    ]
