# Generated by Django 4.1 on 2024-01-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0007_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="community/images/%Y/%m/%d/"),
        ),
    ]
