# Generated by Django 4.1 on 2024-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0010_rename_head_image_question_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
