# Generated by Django 4.1 on 2024-01-09 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0011_alter_question_image_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"managed": False},
        ),
    ]
