# Generated by Django 4.1 on 2024-01-09 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0012_alter_answer_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="answer",
            table="community_answer",
        ),
        migrations.AlterModelTable(
            name="comment",
            table="community_comment",
        ),
        migrations.AlterModelTable(
            name="question",
            table="community_question",
        ),
    ]
