# Generated by Django 4.1 on 2024-01-03 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_birds_delete_m_birds"),
    ]

    operations = [
        migrations.DeleteModel(
            name="birds",
        ),
    ]
